apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-microservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hariramprasanth/istio-learnings.git
    targetRevision: HEAD
    path: customer-order-service/order-service
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
   automated:
    selfHeal: true
    prune: true