apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx-load-balancer
spec:
  host: nginx-service
  subsets:
  - name: v1
    labels:
      version: "1"
  - name: v2
    labels:
      version: "2"
  trafficPolicy:
      outlierDetection:
        consecutive5xxErrors: 2
        interval: 10s
        baseEjectionTime: 20s
        maxEjectionPercent: 100