
# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: canary-gateway
# spec:
#   selector:
#     istio: ingressgateway 
#   servers:
#   - port:
#       number: 80
#       name: http
#       protocol: HTTP
#     hosts:
#     - "*"
# ---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-app-vs
spec:
  hosts:
    - 'nginx-app-v1'
  http:
  - route:
    - destination:
        host: nginx-app-v2
     # weight: 50
    # - destination:
    #     host: nginx-app-v1
    #   weight: 50

