apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-v1
spec:
  selector:
    matchLabels:
      app: nginx-app-v1
  template:
    metadata:
      labels:
        app: nginx-app-v1
    spec:
      containers:
      - name: nginx-app-v1
        image: hariramprasanth/my-nginx:v1
        ports:
        - containerPort: 80
          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-v2
spec:
  selector:
    matchLabels:
      app: nginx-app-v2
  template:
    metadata:
      labels:
        app: nginx-app-v2
    spec:
      containers:
      - name: nginx-app-v2
        image: hariramprasanth/my-nginx:v2
        ports:
        - containerPort: 80
          
---         
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-v1
spec:
  selector:
    app: nginx-app-v1
  ports:
  - port: 80
---         
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-v2
spec:
  selector:
    app: nginx-app-v2
  ports:
  - port: 80

