apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-gw-service
  name: customer-gw-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port:  80
    protocol: TCP
  selector:
    app: istio-ingressgateway
    istio: ingressgateway