apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: customers-destination-rule
spec:
  host: customers-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 1000
        maxRequestsPerConnection: 10
        # http2MaxRequests: 5      