apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: customers-destination-rule
spec:
  host: customers-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 50
      http:
        http1MaxPendingRequests: 25
     