apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name}}
spec:
  hosts:
  - "*"
  {{- if .Values.gateway.enabled }}
  gateways:
    - {{ .Values.gateway.name }}
  {{- end}}
  http:
  - route:
    - destination:
        host: {{ .Values.virtualService.destinationHost }}
        port: 
          number: 80