apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name}}
spec:
  hosts:
  - {{ .Values.virtualService.clientHost | quote }}   
  {{- if .Values.gateway.enabled }}
  gateways:
    - {{ .Values.gateway.name }}
  {{- end}}
  http:
  - route:
    - destination:
        host: {{ .Values.virtualService.destinationHost }}
        port: 
          number: 80
    retries:
      attempts: 5
      perTryTimeout: 10s
      retryOn: connect-failure,refused-stream,503,500
    timeout: 20s