apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2-deployment
  labels:
    app: app-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - name: app-2
        image: hariramprasanth/my-nginx:v2

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-2-service
  name: app-2-service
spec:
  type: ClusterIP
  ports:
  - name: http-app-2
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-2
