kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: tracking-virtual-service
  labels:
    virtualservice: tracking-virtual-service
spec:
  http:
    - route:
        - destination:
            host: tracking-service
  hosts:
    - tracking-service