kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: tracking-virtual-service
  labels:
    virtualservice: tracking-virtual-service
spec:
  http:
    - route:
        - destination:
            host: tracking-service
      retries:
        attempts: 2
        perTryTimeout: 1s
        retryOn: 500,502,200,504,503
      timeout: 15s
  hosts:
    - tracking-service