---
kind: Service
apiVersion: v1
metadata:
  name: app-1-service
spec:
  selector:
    app: app-1
  ports:
  - port: 80
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-deployment
spec:
  selector:
    matchLabels:
      app: app-1
  replicas: 1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.12-alpine
        ports:
        - containerPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-1-destination-rule
spec:
  host: app-1-service
  trafficPolicy:
    tls:
      mode: DISABLE

### modes
### DISABLE, SIMPLE, MUTUAL, ISTIO_MUTUAL