kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: orders-virtual-service
  labels:
    virtaulservice: orders-virtual-service
spec:
  http:
    - route:
        - destination:
            host: orders-service
  hosts:
    - orders-service