kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: orders-virtual-service
  labels:
    virtaulservice: orders-virtual-service
spec:
  http:
    - route:
        - destination:
            host: orders-service
      # retries:
      #   attempts: 2
      #   perTryTimeout: 10s
      #   retryOn: connect-failure,refused-stream,503,500,502
  hosts:
    - orders-service