apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: orders-destination-rule
spec:
  host: orders-service
  trafficPolicy:
    # connectionPool:
    #   tcp:
    #     maxConnections: 50
    #   http:
    #     maxRequestsPerConnection: 1
    #     http2MaxRequests: 1
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 60s
      maxEjectionPercent: 100
      minHealthPercent: 0